#pragma once

#ifndef _INTERGEN_GENERATED__engine_LUA_H_
#define _INTERGEN_GENERATED__engine_LUA_H_

//@file Lua interface file for engine interface generated by intergen
//See LICENSE file for copyright and license information

#include "../engine.h"

#include <comm/intergen/ifc.lua.h>
#include <comm/token.h>

namespace xt {
namespace lua {

class engine
{
public:
};

} //namespace lua
} //namespace


#endif //_INTERGEN_GENERATED__engine_LUA_H_
