#pragma once

#ifndef _INTERGEN_GENERATED__engine_JS_H_
#define _INTERGEN_GENERATED__engine_JS_H_

//@file Javascript interface file for engine interface generated by intergen
//See LICENSE file for copyright and license information

#include "../engine.h"

#include <comm/intergen/ifc.js.h>
#include <comm/token.h>

namespace xt {
namespace js {

class engine
{
public:
};

} //namespace js
} //namespace


#endif //_INTERGEN_GENERATED__engine_JS_H_
