#pragma once

#ifndef __INTERGEN_GENERATED__engine_LUA_H__
#define __INTERGEN_GENERATED__engine_LUA_H__

//@file Lua interface file for engine interface generated by intergen
//See LICENSE file for copyright and license information

#include "engine.h"

#include <comm/intergen/ifc.lua.h>
#include <comm/token.h>

namespace xt {
namespace lua {

class engine
{
public:

    ///Interface creator
    //@param script - script for object to bind to
    //@param bindvar - name of variable in script context for object to bind to
    //@param ctx -
    static iref<xt::engine> get( lua_State * L, const ::lua::script_handle& script, const coid::token& bindvar = coid::token(), iref<::lua::registry_handle>* ctx = 0)
    {
        typedef iref<xt::engine> (*fn_bind)(lua_State * L, const ::lua::script_handle&, const coid::token&, iref<::lua::registry_handle>*);
        static fn_bind binder = 0;
        static const coid::token ifckey = "xt::engine.get@creator.lua";

        if(!binder)
            binder = reinterpret_cast<fn_bind>(
                coid::interface_register::get_interface_creator(ifckey));

        if(!binder)
            throw coid::exception("interface binder inaccessible: ") << ifckey;

        return binder(L, script, bindvar, ctx);
    }
};

} //namespace lua
} //namespace


#endif //__INTERGEN_GENERATED__engine_LUA_H__
